import { registerSource } from '@postdeck/core'
import { markdownFactory } from './markdown.js'
import { astroCollectionFactory } from './astro-collection.js'
import { notionFactory } from './notion.js'
registerSource('markdown', markdownFactory)
registerSource('astro-collection', astroCollectionFactory)
registerSource('notion', notionFactory)
export * from './frontmatter.js'
export * from './localfs.js'
export { markdownFactory } from './markdown.js'
export { astroCollectionFactory } from './astro-collection.js'
export { notionFactory } from './notion.js'
export { loadPosts, loadProjects } from './engine.js'
export type { ProjectView } from './engine.js'
export { resolveConfigPath, loadBlogsConfig } from './config-loader.js'
export { gatherToneContext } from './tone.js'
export { createAnthropicLLM } from './anthropic-llm.js'
export { createGeminiLLM } from './gemini-llm.js'
export { createOpenAILLM } from './openai-llm.js'
export { selectLLM } from './llm-select.js'
export { blocksToMarkdown } from './notion-blocks.js'
export { buildDeployCommands, deployProject, gitToplevel } from './deploy.js'
